### ISSUE TITLE
Failed to install turtlebot drivers 

### ISSUE THREAD

**Issue by goelshivam1210** [ros2/turtlebot2_demo#100]
## Bug report

**Required Info:**

- Operating System:
   Ubuntu 18.04
  - 
- Installation type:
Source
  - 
- Version or commit hash:
  - 
- DDS implementation:
  - 
- Client library (if applicable):
  - 
turtlebot_drivers
#### Steps to reproduce issue

```

```

#### Actual behavior

Failed   <<< turtlebot2_drivers [30.0s, exited with code -11]                                         

#### Additional information
I am trying to install turtlebot2 drivers following the instructions in the repository. 
I cannot successfully install the turtlebot2 drivers and therefore I cannot successfully use the demo.

I have reached to a point where I have successfully installed ros2-bouncy from source. Installed ros-melodic. But when I try to build the ros1 libraries it throws an error. 
Specifically. I run 
```colcon build --symlink-install --packages-select cartographer cartographer_ros turtlebot2_amcl turtlebot2_cartographer turtlebot2_drivers turtlebot2_follower turtlebot2_teleop```

and I get
```
Starting >>> turtlebot2_drivers
Starting >>> cartographer                        
Failed   <<< turtlebot2_drivers [30.0s, exited with code -11]                                         
Aborted  <<< cartographer [8min 15s]                                          
                                      
Summary: 0 packages finished [8min 17s]
  1 package failed: turtlebot2_drivers
  1 package aborted: cartographer
  1 package had stderr output: cartographer
  5 packages not processed
```

Any help in this regard will be deeply appreciated. I am new to ros2, so sorry for noob questions.

----

**Comment by clalancette** [comment]
ROS 2 Bouncy has been end-of-life for several years.  This repository hasn't been maintained in quite a while either.  Most of what was going on in this repository has been moved elsewhere.  We really should archive this repository, but we just haven't gotten around to it yet.

Regardless, you'll have a much better time if you use the newest supported versions (ROS 2 Foxy or Galactic).  You can find instructions on how to install them over at https://docs.ros.org/.  What are you trying to accomplish?

**Comment by clalancette** [comment]
No response in a while, and this repository should really be archived anyway.  I'm going to close this out.
