### ISSUE TITLE
Cannot build the demo

### ISSUE THREAD

**Issue by yongli3** [ros2/turtlebot2_demo#12]
I followed the doc to build the demo, but received the below error messsages, any suggestions/comments?

Built target dumb_teleop
In file included from ros2_ws/src/turtlebot2_demo/turtlebot2_drivers/src/kobuki_node.cpp:40:0:
ros2_ws/install/include/tf2_ros/transform_broadcaster.h:72:32: error: ‘tf2_msgs’ was not declared in this scope
   rclcpp::publisher::Publisher<tf2_msgs::msg::TFMessage>::SharedPtr publisher_;

**Comment by clalancette** [comment]
We recently merged a few pull requests that may help this issue.  Can you pull the latest code and try again?  Thanks!

**Comment by yongli3** [comment]
Thanks @clalancette. I updated to the latest code, and still receive build error messages:
src/turtlebot2_demo/turtlebot2_drivers/src/kobuki_node.cpp:40:0:
ros2_ws/install/include/tf2_ros/transform_broadcaster.h:72:32: error: ‘tf2_msgs’ was not declared in this scope
   rclcpp::publisher::Publisher<tf2_msgs::msg::TFMessage>::SharedPtr publisher_;

**Comment by yongli3** [comment]
Switched ROS 2 branch from beta1 to master, the build issue was fixed!

**Comment by clalancette** [comment]
Ah, great.  Yeah, the new development is on master, I should have mentioned that.

Since this issue seems to be fixed, I'm going to close this out.

**Comment by dirk-thomas** [comment]
> Since this issue seems to be fixed, I'm going to close this out.

@clalancette Did you intend to close this ticket?

**Comment by clalancette** [comment]
Heh, I did, and I clicked the wrong button.  Thanks.
