### ISSUE TITLE
Land a node to do teleop from the keyboard

### ISSUE THREAD

**Issue by clalancette** [ros2/turtlebot2_demo#36]
While a keyboard teleop isn't the best, it is better than nothing if you don't have a joystick handy.  We should land the keyboard teleop code that is available in [this branch](/ros2/turtlebot2_demo/tree/teleop)

**Comment by mikaelarguedas** [comment]
Agreed that a keyboard teleop is always handy. IMO the ROS1 repo should be forked and the package ported, because I don't see any real advantage of having this package in the turtlebot2_demo repo

**Comment by Kukanani** [comment]
I'll take this on.

**Comment by mikaelarguedas** [comment]
:+1: Given that it's a nice to have, I think that this node could be a good case study of how to port code in a more ROS2 way (inherit from node, build it as a shared library that can be loaded as a component etc). Thanks @Kukanani !

**Comment by clalancette** [comment]
Yeah, that sounds good to me.

**Comment by mikaelarguedas** [comment]
I thought this was a c++ package like the joystick one. Discard my comment about making this an experiment for porting in a ROS2 shared library way then...

**Comment by mikaelarguedas** [comment]
CI for this (though this is a python node so CI won't validate much):
* TB2 Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_turtlebot-demo_linux&build=55)](http://ci.ros2.org/job/ci_turtlebot-demo_linux/55/)
* TB2 Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_turtlebot-demo_linux-aarch64&build=73)](http://ci.ros2.org/job/ci_turtlebot-demo_linux-aarch64/73/)
