### ISSUE TITLE
Pose2D needs to be replaced in file kobuki_node.cpp to LegacyPose2D

### ISSUE THREAD

**Issue by vdiluoffo** [ros2/turtlebot2_demo#5]
I did find that in kobuki.hpp the usage of ecl::LegacyPose2D is different from kobuki_node.cpp, which was ecl::Pose2D at lines 99 and 102. I changed them and the build works for beta1/rti.

**Comment by rohbotics** [comment]
Can you submit these changes as a pull request?

**Comment by vdiluoffo** [comment]
I tried to upload a new file and push a commit, but I don't have write access. Unless, I should be doing something different via the web interface?

**Comment by rohbotics** [comment]
You can fork the repo, make/upload the changes on your fork, then submit a pull request to this repo. 
https://help.github.com/articles/fork-a-repo/
https://help.github.com/articles/about-pull-requests/

This way the people with write access can merge your changes into this repository.
