### ISSUE TITLE
Turtlebot2_cartographer mapping overlay 

### ISSUE THREAD

**Issue by yechun1** [ros2/turtlebot2_demo#60]
we run the demo "turtlebot2_cartographer/launch/turtlebot_carto_2d.py" on turtlebot2 by Hokuyo laser(enabled urg_node) , but the mapping meet overlays while turn round the robot.    
 - Not sure If community met same issues as below pic?
 - Not see flat_world_imu_node_main.cc(from ROS1) is porting to ROS2, will it be the root cause?

Mapping with Hokuyo UTM-30LX
![cartographer_mapping_with_laser](https://user-images.githubusercontent.com/10727041/29100695-cc02e718-7cdf-11e7-9ec8-87aa3a67f427.png)

**Comment by clalancette** [comment]
While we do not have `flat_world_imu_node_main.cc`, I doubt that is the problem.  First, the ROS2 kobuki_node is basically doing the same thing that `flat_world_imu_node_main.cc` is (namely, dropping data that is timestamped in the past).  Second, if cartographer ever gets IMU data in the past, it simply crashes.

As for the overall issue, we only tried it on small areas, which worked OK but not great.  Unfortunately, there are a lot of sources of error :(.  Some of that comes from the odometry/gyro down at the platform level, some of it comes from the Astra camera, and some of it probably comes from the cartographer configuration.  If anyone feels like playing around with the configuration and/or improving the sources of error, it would be great.

**Comment by allenh1** [comment]
Could you post the hokuyo config file?

**Comment by TonyGuo236** [comment]
I guess this issue was caused by imu/odometry published by kobuki, we (Chris and I) will look into it. actually we also used Astra camera but the map is messy (i am not sure if it is the camera problem, i am switch to ROS1 for a check) in very small place. we will paste launch file and hokuyo config file later.

**Comment by yechun1** [comment]
Here is the patch include hokuyo config file: 
https://github.com/ros2/turtlebot2_demo/pull/61/commits/e8a946f37cb7f8d6e1a669085c8cd15d38c2a15a

**Comment by allenh1** [comment]
@yechun1 I left some feedback for the config file for you on #61. I think the parameters need some tweaking, I suggested values for you there.

**Comment by yechun1** [comment]
Close the issue  (https://github.com/ros2/turtlebot2_demo/pull/61)

![cartographer_20meter_30lx_lab-2](https://user-images.githubusercontent.com/10727041/29265110-58b0c320-8112-11e7-92c3-516c5e392fa3.png)

**Comment by allenh1** [comment]
@yechun1 nice! Is this with the new parameters?

**Comment by yechun1** [comment]
@allenh1, we use ROS1 config file [turtlebot_urg_lidar_2d.lua](https://github.com/googlecartographer/cartographer_turtlebot/blob/master/cartographer_turtlebot/configuration_files/turtlebot_urg_lidar_2d.lua) and apply on ROS2.  Here is config file (e66f4ed) which only change max_range=20 (for 30m Lidar but could not reach 30 as computing limitation)
