### ISSUE TITLE
Test cartographer demo in bouncy and fix configuration files if needed

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/turtlebot2_demo#85]
At bouncy testing time we should try the `turtlebot_cartographer` demo and modify the configuration files if needed as the set of parameter changed quite a bit since we originally ported.

We can use the [official `cartographer_turtlebot` 0.3.0 configuration files](https://github.com/googlecartographer/cartographer_turtlebot/tree/0.3.0/cartographer_turtlebot/configuration_files) as a reference

**Comment by wjwwood** [comment]
@mikaelarguedas to close, possibly with something in the README.

**Comment by mikaelarguedas** [comment]
Closing, readme update PR at https://github.com/ros2/turtlebot2_demo/pull/93
