### ISSUE TITLE
Cartographer demo should be updated to use rviz plugins for submap displays

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/turtlebot2_demo#94]
follow-up of https://github.com/ros2/turtlebot2_demo/issues/85

### Implementation consideration

May be worth upgrading the code to cartographer 1.0 before porting `cartographer_rviz`

**Comment by clalancette** [comment]
This has been done elsewhere, and this repository hasn't been supported in years. Closing to archive the whole repository.
