### ISSUE TITLE
Create 2 Base Support in ROS2 Turtlebot Demo

### ISSUE THREAD

**Issue by OrBeProgrammed** [ros2/turtlebot2_demo#96]
## Feature request
Support Create 2 iRobot base, other 3d sensors.
#### Feature description
In ROS Kinetic, one can use the iRobot Create 2 base for a turtlebot_demo by updating .bashrc:
export TURTLEBOT_BASE=create
export TURTLEBOT_STACKS=circles
export TURTLEBOT_3D_SENSOR=asus_xtion_pro    (alternatively kinect)

Because this robot is still actively sold and marketed, it would be very helpful to have this same option. It is a very affordable option to try the turtlebot demos and it was easy to do with Kinetic.

**Comment by OrBeProgrammed** [comment]
There is also this calibration option in the original ROS turtlebot create tutorial:
http://wiki.ros.org/turtlebot_calibration/Tutorials/Calibrate%20Odometry%20and%20Gyro

**Comment by allenh1** [comment]
@lukewebdev I actually started working on a port for ~~Turtlebot3~~ Turtlebot (with create base) that you can find [here](https://github.com/allenh1/turtlebot_create).

There's an open PR there that has most of the `create_node` working. I'm definitely willing to take a look at this again some point in the near future, but you're more than welcome to collaborate if you want some more progress on it!

Cheers.

**Comment by OrBeProgrammed** [comment]
Thanks Allen, I will check it out!  Just for future clarity on this post, can you explain what you mean by "Turtlebot3 (with create base)"?  I thought by definition a Turtlebot3 used dynamixel drive train and a Turtlebot2 used Kobuki or Create 2?

**Comment by allenh1** [comment]
> Just for future clarity on this post, can you explain what you mean by "Turtlebot3 (with create base)"?

I meant "I need to drink coffee before writing things on GitHub," I think. ;)

Turtlebot2 uses the Kobuki only (as far as I know), and Turtlebot uses the create base. As someone owning a Turtlebot with the create base, I would love to get Turtlebot going in ROS 2 (and got decently far with the process).

**Comment by OrBeProgrammed** [comment]
That sounds great. I have both a Create 2 base and the Kobuki based-turtlebot so I would love to help with this.

**Comment by allenh1** [comment]
@lukeweb after looking at it, I remembered the big slow down: there's no `tf2_py` yet! I'll look into that some.

**Comment by lukeweb** [comment]
@allenh1 Sorry mate, but I think you included the wrong person :D He's @lukewebdev ;)

**Comment by OrBeProgrammed** [comment]
Never fear, I am set up to get all notices from this thread.

**Comment by clalancette** [comment]
This has been done elsewhere, and this repository hasn't been supported in years. Closing to archive the whole repository.
