### ISSUE TITLE
can this demo run on ROS2 dashing?

### ISSUE THREAD

**Issue by pqLee** [ros2/turtlebot2_demo#99]
## Bug report

**Required Info:**

- Operating System:
  - 
- Installation type:
  - 
- Version or commit hash:
  - 
- DDS implementation:
  - 
- Client library (if applicable):
  - 

#### Steps to reproduce issue

```

```

#### Additional information

----

**Comment by clalancette** [comment]
Sort of.  There is an open pull request #98 that goes some way to make this compile/work on Dashing, but it is held up by some of the underlying libraries not yet being available in ROS 2 quite yet.  In particular, you also need https://github.com/yujinrobot/kobuki_core/pull/43 and maybe one other pull request.  We are (slowly) working towards resolving all of this and releasing into Dashing and Eloquent, but it may take some time.

**Comment by dirk-thomas** [comment]
Closing this ticket since the question has been answered and other tickets already exist to convert the remaining work.
